apiVersion: apps/v1
kind: Deployment
metadata:
  name: treasurebook-api
spec:
  replicas: 3  # Initial replicas
  selector:
    matchLabels:
      app: treasurebook-api
  template:
    metadata:
      labels:
        app: treasurebook-api
    spec:
      containers:
      - name: treasurebook-api
        image: treasurebook-api:latest  # Image from Docker
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: treasurebook-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: treasurebook-api
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 5
